name = "forgnu"
version = "0.1.0"
license = "license"
author = "Seyed Ali Ghasemi"
maintainer = "info@gha3mi.com"
copyright = "Copyright 2023, Seyed Ali Ghasemi"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"